/**
 * Data Explorer Service
 * API Service that reads from Elasticsearch.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FacetValue from './FacetValue';





/**
* The TimeSeriesFacetValue model module.
* @module model/TimeSeriesFacetValue
* @version 0.0.1
*/
export default class TimeSeriesFacetValue {
    /**
    * Constructs a new <code>TimeSeriesFacetValue</code>.
    * A list of facet values in a time series.
    * @alias module:model/TimeSeriesFacetValue
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TimeSeriesFacetValue</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TimeSeriesFacetValue} obj Optional instance to populate.
    * @return {module:model/TimeSeriesFacetValue} The populated <code>TimeSeriesFacetValue</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeSeriesFacetValue();

            
            
            

            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Number');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [FacetValue]);
            }
        }
        return obj;
    }

    /**
    * Value used for time series.
    * @member {Number} time
    */
    time = undefined;
    /**
    * @member {Array.<module:model/FacetValue>} values
    */
    values = undefined;








}


